version: '3'

volumes:
  dbdata:
services:
  web:
    build: .
    depends_on:
      - db
    ports: 
      - 80:80
      - 443:443
    volumes:
      - .:/var/www/decosur:cached
    links:
      - db
  db:
    image: mysql:5.7
    ports: 
      - 3306:3306
    volumes:
      - ./database/dbdata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel